<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Chemical Elements' => 'Химические элементы',
    'Chemical Elements ID' => 'Номер химического элемента',
    'Chemical Formula' => 'Химическая формула',
    'Chemical Reactions' => 'Химические реакции',
    'Chemical Reactions ID' => 'Номер химической реакции',
    'Chemicals' => 'Химические вещества',
    'Chemicals ID' => 'Номер химического вещества',
    'Create Chemical Elements' => 'Добавить химический элемент',
    'Create Chemical Reactions' => 'Добавить химическую реакцию',
    'Create Chemicals' => 'Добавить химическое вещество',
    'Create Elements Of Chemicals' => 'Добавить элемент к веществу',
    'Create Reaction Reagents' => 'Добавить элемент к реакции',
    'Delete' => 'Удалить',
    'Elements Of Chemicals' => 'Элементы вещества',
    'Group Number' => 'Номер группы',
    'ID' => 'Номер',
    'Items Name' => 'Наименование элемента',
    'Latin Name' => 'Латинское наименование',
    'Mass' => 'Масса',
    'Molecular Weight' => 'Молекулярная масса',
    'Oxidation' => 'Степень оксисления',
    'Oxidation Stage' => 'Степень окисления',
    'Period Number' => 'Номер периода',
    'Ram' => 'Относительная атомная масса',
    'Reaction Reagents' => 'Элементы реакций',
    'Reaction Type' => 'Тип реакции',
    'Reset' => 'Отменить',
    'Result' => 'Результат',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Subgroup' => 'Подгруппа',
    'Substance Name' => 'Наименование вещества',
    'Symbol' => 'Символ',
    'The requested page does not exist.' => '',
    'Update' => 'Обновить',
    'Update Chemical Elements: {name}' => '',
    'Update Chemical Reactions: {name}' => '',
    'Update Chemicals: {name}' => '',
    'Update Elements Of Chemicals: {name}' => '',
    'Update Reaction Reagents: {name}' => '',
];
